### PR TITLE
🐛 Update the dependency resolution mechanism in freeze

### PR DESCRIPTION
**Pull request by yogyagamage**
Fixes 

- https://github.com/chains-project/maven-lockfile/issues/687
- https://github.com/chains-project/maven-lockfile/issues/686
- https://github.com/chains-project/maven-lockfile/issues/683
 - Adds a new field "included" to the lockfile to track the dependency conflict resolution.

### CODE REVIEW

**Comment by algomaster99** [comment]
@yogyagamage It is surprising that no tests are failing which means this functionality was not well tested before. Could you please add a test case that exercises `getNearestDependency`?

**Comment by yogyagamage** [comment]
> @yogyagamage It is surprising that no tests are failing which means this functionality was not well tested before. Could you please add a test case that exercises `getNearestDependency`?

Added a test case https://github.com/chains-project/maven-lockfile/pull/702/commits/cb1aa05ba539276f2918f8e70b6ac092338fcc3a

**Comment by algomaster99** [comment]
Sorry couldn't review. But we had discussed this in meeting so it's okay.

________________________________

**Comment by yogyagamage** [comment]
No worries, I just merged it because I needed the changes to add a new PR.

**Pull request merged**
